/*
 * File: app/store/TDSUVRec.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TDSUVRec', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.TDSUVRec',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.TDSUVRec',
            storeId: 'TDSUVRec',
            data: [
                {
                    recID: '4',
                    recType: 'UnVerified Valid Records More than 4 months'
                },
                {
                    recID: '3',
                    recType: 'UnVerified Valid Records More than 3 months'
                },
                {
                    recID: '1',
                    recType: 'UnVerified InValid Records More than 1 months'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});