/*
 * File: app/view/FiscalYearRegenerate.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FiscalYearRegenerate', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    frame: true,
    title: 'Fiscal Year Re-Generate',

    layout: {
        type: 'table',
        columns: 2
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'txtCurrentFiscalYear',
                    margin: '20 0 0 50',
                    fieldLabel: 'Current Fiscal Year',
                    labelWidth: 130,
                    fieldStyle: 'background-color:#D2D2D2;background-image:none;'
                },
                {
                    xtype: 'textfield',
                    itemId: 'txtPreviousFiscalYear',
                    margin: '20 0 0 50',
                    fieldLabel: 'Previous Fiscal Year',
                    labelWidth: 130,
                    fieldStyle: 'background-color:#D2D2D2;background-image:none;'
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    height: 28,
                    margin: '30 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnRegenerate',
                            padding: 5,
                            text: 'Re-Generate',
                            listeners: {
                                click: {
                                    fn: me.onBtnRegenerateClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onPanelAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onBtnRegenerateClick: function(button, e, eOpts) {
        var currentFiscalYear=Ext.ComponentQuery.query('#txtCurrentFiscalYear')[0];
        var previousFiscalYear=Ext.ComponentQuery.query('#txtCurrentFiscalYear')[0];

        var errMsg='';
        if(currentFiscalYear.getValue()===null ||currentFiscalYear.getValue()==="")
            {
                errMsg+="Please,Enter Current Fiscal Year";
            }
        if(previousFiscalYear.getValue()===null ||previousFiscalYear.getValue()==="")
            {
                errMsg+="Please,Enter Previous Fiscal Year";
            }
        if(errMsg!=='')
            {
                msg("WARNING",errMsg);
                return;
            }

        Ext.Msg.confirm('Confirm Action', 'Do you want to Re-generate Fiscal Year ?', function(btn) {
            if(btn == 'yes'){

                 var objRegenerateFiscalYearClosing={
                 OfficeCode:getOfficeCode(),
                 NewFiscalYear:currentFiscalYear.getValue(),
                 OldFiscalYear:previousFiscalYear.getValue()};

                var wMsg='Deleting....';

                var waitSave = watiMsg(wMsg);

                Ext.Ajax.request({
                            url: '../Handlers/Finance/AccountTransaction/RegenerateFiscalYearClosingHandler.ashx',
                            params: {
                                method:'SaveRegenerateFiscalYearClosing',
                                regenerateFiscalYearClosing:JSON.stringify(objRegenerateFiscalYearClosing)
                            },
                            success: function(response){
                            waitSave.hide();
                            var out=Ext.decode(response.responseText);
                            console.log(out);

                            if(out.success==="true")
                                {
                                    var message=out.root;

                                    msg("SUCCESS",message.OutResultMessage,function(){

                                    });




                                }
                                else
                                    {
                                        msg("FAILURE",out.message);
                                    }
                            },
                            failure: function ( result, request ) {
                                waitSave.hide();
                                var out=Ext.decode(response.responseText);
                                msg("FAILURE",out.message);
                            }

                        });



                return true;
            }
        });
    },

    onPanelAfterRender: function(component, eOpts) {
        Ext.ComponentQuery.query('#txtCurrentFiscalYear')[0].setValue(getFiscalYear());
        Ext.ComponentQuery.query('#txtPreviousFiscalYear')[0].setValue('');
    }

});