/*
 * File: app/controller/MSControlValues.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MSControlValues', {
    extend: 'Ext.app.Controller',

    stores: [
        'MsControlValuesStore',
        'MsReferenceValuesStore'
    ],

    onFrmMsControlValuesAfterRender: function(component, eOpts) {
        var name =null;
        Ext.Ajax.request({
        		    url: '../Handlers/GeneralMasterParameters/References/MsControlValuesHandler.ashx?method=GetMsControlValues',
                    method:'POST',
                    params:{name:name},
                    success: function ( result, request ) {

                        var obj = Ext.decode(result.responseText);
                        var data = obj.root;
        				console.log('data',data);
        				var strMsControlValues = Ext.getStore('MsControlValuesStore');
                        strMsControlValues.add(data);


        				//storeAcLines.add(data.AppealLinesLST);
        				console.log('storeAcLines',strMsControlValues);



                    }


                });

        Ext.ComponentQuery.query('#btnReferenceValues')[0].disable(true);

    },

    onBtnControlValuesClick: function(button, e, eOpts) {
         var store =Ext.getStore('MsControlValuesStore');
         var rec={NameEn:'',
                  ControlValue:'',
                  Remarks:'',
                  Action:'I'};
                store.add(rec);
    },

    onBtnReferenceValuesClick: function(button, e, eOpts) {
         var store =Ext.getStore('MsReferenceValuesStore');
         var rec={RefMstCode:'',
                  RefMstName:'',
                  Action:'I'};
                store.add(rec);
    },

    init: function(application) {
        this.control({
            "#frmMsControlValues": {
                afterrender: this.onFrmMsControlValuesAfterRender
            },
            "#btnControlValues": {
                click: this.onBtnControlValuesClick
            },
            "#btnReferenceValues": {
                click: this.onBtnReferenceValuesClick
            }
        });
    }

});
