/*
 * File: app/view/CreditClaim.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CreditClaim', {
    extend: 'Ext.panel.Panel',

    frame: true,
    height: 1000,
    id: '',
    itemId: 'pnlCreditClaim',
    autoScroll: false,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: ' कर मिलान दावीको विवरण राख्ने(अनुसूची -१०)',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    frame: true,
                    height: 950,
                    itemId: 'frm_CreditClaim',
                    margin: 5,
                    autoScroll: true,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'container',
                            frame: true,
                            height: 125,
                            itemId: 'cntHeaderCreditClaim',
                            margin: '0 0 5 0',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 50,
                                    margin: '2 0 0 70',
                                    style: 'font-size:20px;\r\ntext-align:center;',
                                    text: ' कर मिलान दावीको विवरण राख्ने(अनुसूची -१०)'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 30,
                                    maxHeight: 30,
                                    layout: {
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            height: 25,
                                            hidden: false,
                                            id: '',
                                            itemId: 'hdnlblCreditClaimAction',
                                            maxHeight: 25,
                                            width: 196,
                                            fieldStyle: '{color:red;}',
                                            fieldLabel: '',
                                            hideLabel: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    height: 25,
                                    hidden: true,
                                    itemId: 'dispCreditClaim_submissionNo',
                                    maxHeight: 25,
                                    width: 245,
                                    fieldLabel: 'सब्मिशन नं',
                                    labelWidth: 150
                                },
                                {
                                    xtype: 'container',
                                    height: 25,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'CreditClaim_IROName',
                                            width: 440,
                                            fieldLabel: 'आन्तरिक राजस्व कार्यालयको नाम',
                                            labelSeparator: ' ',
                                            labelWidth: 180
                                        },
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            hidden: false,
                                            itemId: 'txtCC_ASSESSMENTNO',
                                            margin: '',
                                            fieldLabel: 'कर मिलान दावी नं',
                                            labelWidth: 90,
                                            enableKeyEvents: true,
                                            maxLength: 12,
                                            minLength: 12,
                                            size: 12
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            frame: true,
                            height: 360,
                            margin: '0 0 5 0',
                            layout: {
                                columns: 6,
                                type: 'table'
                            },
                            bodyPadding: 10,
                            collapseFirst: false,
                            collapsible: false,
                            title: '१  कर मिलान दावीको विवरण राख्ने विवरण',
                            titleCollapse: false,
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'extTbl',
                                    height: 350,
                                    layout: {
                                        columns: 6,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            colspan: 3,
                                            itemId: 'txtCC_PanNo',
                                            margin: '5px 0 0 0',
                                            fieldLabel: 'स्था . ले . नं .*',
                                            labelWidth: 80,
                                            allowBlank: false,
                                            emptyText: '',
                                            enableKeyEvents: true,
                                            enforceMaxLength: true,
                                            maskRe: /[0-9]/,
                                            maxLength: 9,
                                            minLength: 9,
                                            size: 9
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'ddlCCActType',
                                            margin: '5 0 0 20',
                                            fieldLabel: 'खाताको किसिम*',
                                            allowBlank: false,
                                            emptyText: '-- छान्नुहोस् --',
                                            displayField: 'IncomeTaxAcctTypeName',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'IncomeTaxAcctType',
                                            typeAhead: true,
                                            valueField: 'IncomeTaxAcctTypeID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 6,
                                            itemId: 'txtCC_Name',
                                            margin: '5 0 0 7',
                                            readOnly: true,
                                            fieldLabel: 'नाम ',
                                            labelWidth: 30,
                                            size: 60
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 1,
                                            margin: '5px 0 0 0',
                                            style: 'margin-right:45px;',
                                            text: 'ठेगाना '
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '5px 0 0 0',
                                            style: 'margin-right:30px;',
                                            text: 'घर नं .'
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '5px 0 0 0',
                                            style: 'margin-right:30px;',
                                            text: 'वार्ड नं .'
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '5px 0 0 0',
                                            style: 'margin-right:30px;',
                                            text: 'गांउ / टोल र बाटोको नाम'
                                        },
                                        {
                                            xtype: 'radiogroup',
                                            itemId: 'CC_VM',
                                            margin: '5px 0 0 0',
                                            width: 200,
                                            fieldLabel: '',
                                            columns: 2,
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rdl_CC_Metro_Mun',
                                                    readOnly: true,
                                                    boxLabel: 'म. न. पा.'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rdl_CC_Sub_Metro_Mun',
                                                    readOnly: true,
                                                    boxLabel: 'उ. म. न. पा.'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rdl_CC_Mun',
                                                    readOnly: true,
                                                    boxLabel: 'न. पा.'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rdl_CC_VDC',
                                                    readOnly: true,
                                                    boxLabel: 'गा. वि. स.'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'label',
                                            margin: '5px 0 0 0',
                                            style: 'margin-right:50px;',
                                            text: 'जिल्ला'
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 2,
                                            itemId: 'txtCC_HouseNo',
                                            margin: '5 0 0 90',
                                            width: 50,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtCC_WardNo',
                                            margin: '',
                                            width: 50,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtCC_ToleName',
                                            margin: '',
                                            width: 140,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtCC_VDCName',
                                            margin: '',
                                            width: 200,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtCC_DistrictName',
                                            margin: '',
                                            width: 100,
                                            size: 100
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 2,
                                            itemId: 'txtCC_Phone',
                                            margin: '5px 0 0 0',
                                            width: 150,
                                            readOnly: true,
                                            fieldLabel: 'फोन ',
                                            labelWidth: 60,
                                            enforceMaxLength: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 2,
                                            itemId: 'txtCC_Mobile',
                                            margin: '5px 0 0 0',
                                            width: 207,
                                            readOnly: true,
                                            fieldLabel: 'मोबाइल ',
                                            labelWidth: 62
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 2,
                                            itemId: 'txtCC_Email',
                                            margin: '5px 0 0 0',
                                            width: 340,
                                            readOnly: true,
                                            fieldLabel: 'इमेल ',
                                            labelWidth: 60
                                        },
                                        {
                                            xtype: 'combobox',
                                            colspan: 3,
                                            itemId: 'ddlCC_FiscalYear',
                                            margin: '10 0 0 0',
                                            fieldLabel: 'आ.ब.*',
                                            labelWidth: 65,
                                            emptyText: '-- छान्नुहोस् - -',
                                            displayField: 'fiscalYear',
                                            forceSelection: true,
                                            store: 'FiscalYear',
                                            typeAhead: true,
                                            valueField: 'fiscalYear'
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 4,
                                            width: 400,
                                            text: '( भर्ने उदाहरण २०६२.०६३ )'
                                        },
                                        {
                                            xtype: 'textfield',
                                            colspan: 3,
                                            itemId: 'txtCC_ClainDate',
                                            margin: '5 0 0 0',
                                            fieldLabel: 'दावी मिति*',
                                            labelWidth: 60,
                                            allowBlank: false,
                                            emptyText: 'YYYY.MM.DD',
                                            maskRe: /[0-9.]/,
                                            size: 10
                                        },
                                        {
                                            xtype: 'displayfield',
                                            colspan: 6,
                                            itemId: 'CC_TpOfficeType',
                                            width: 400,
                                            fieldLabel: 'करदाताको स्थिति '
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            frame: true,
                            itemId: '',
                            margin: 5,
                            autoScroll: true,
                            bodyPadding: 10,
                            title: '२   कर मिलान दावीको विवरण राख्ने विवरण (अनुसूची -१०)',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'cntTblAnx1',
                                    margin: '0 0 0 150',
                                    layout: {
                                        columns: 1,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'cboCCType',
                                            fieldLabel: 'कर दावीको किसिम *',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            emptyText: '---छान्नुहोस्.---',
                                            displayField: 'ClaimName',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'ClaimTypeD03',
                                            typeAhead: true,
                                            valueField: 'ClaimID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtFiscalYearCC',
                                            width: 300,
                                            readOnly: true,
                                            fieldLabel: 'आर्थिक वर्ष',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            maxLength: 8
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtCreditTransferFiscalYearCC',
                                            fieldLabel: 'क्रेडिट सारेको आर्थिक वर्ष',
                                            labelAlign: 'right',
                                            labelWidth: 230
                                        },
                                        {
                                            xtype: 'combobox',
                                            hidden: true,
                                            itemId: 'cboAcctNumberCC',
                                            width: 550,
                                            fieldLabel: 'राजश्व शिर्षक नम्वर ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            emptyText: '---छान्नुहोस्.---',
                                            displayField: 'RevActWithCode',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'RevenueAccountAnx10',
                                            typeAhead: true,
                                            valueField: 'AccountCode'
                                        },
                                        {
                                            xtype: 'combobox',
                                            hidden: true,
                                            itemId: 'cboVoucherTypeCC',
                                            fieldLabel: 'दाखीलाको तरिका ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            emptyText: '---छान्नुहोस्.---',
                                            displayField: 'EstPaymentModeName',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'EstPaymentMode',
                                            typeAhead: true,
                                            valueField: 'EstPaymentModeID'
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtVoucherNumCC',
                                            fieldLabel: 'दाखीला निस्सा नम्वर ',
                                            labelAlign: 'right',
                                            labelWidth: 230
                                        },
                                        {
                                            xtype: 'combobox',
                                            hidden: true,
                                            itemId: 'cboBankCC',
                                            width: 550,
                                            fieldLabel: 'बैंकको नाम ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            emptyText: '---छान्नुहोस्.---',
                                            displayField: 'BankName',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'OfficeBankInfo',
                                            typeAhead: true,
                                            valueField: 'BankBr'
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtCreditDateCC',
                                            width: 330,
                                            fieldLabel: 'दाखीला मिति ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            msgTarget: 'side',
                                            emptyText: 'YYYY.MM.DD',
                                            maskRe: /[0-9.]/,
                                            maxLength: 10,
                                            listeners: {
                                                blur: {
                                                    fn: me.onTxtCreditDateAnx10Blur,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtCreditAmtCC',
                                            width: 330,
                                            fieldCls: 'TxtRight',
                                            fieldLabel: 'दाखीला रकम ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            maskRe: /[0-9]/,
                                            maxLength: 10
                                        },
                                        {
                                            xtype: 'combobox',
                                            hidden: true,
                                            itemId: 'cboWithHoldingTypeCC',
                                            width: 550,
                                            fieldLabel: 'अग्रिम कर कट्टीको किसिम ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            emptyText: '---छान्नुहोस्.---',
                                            displayField: 'RevActWithCode',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: 'RevenueAccountAnx10',
                                            typeAhead: true,
                                            valueField: 'AccountCode'
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtWithHoldingPanCC',
                                            fieldLabel: 'अग्रिम म कर कट्टी गर्नेको स्था.ले.नं. (भए) ',
                                            labelAlign: 'right',
                                            labelWidth: 230,
                                            enforceMaxLength: true,
                                            maskRe: /[0-9]/,
                                            maxLength: 9,
                                            minLength: 9
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            itemId: 'txtWithHoldingNameCC',
                                            fieldLabel: 'अग्रिम  कर कट्टी गर्नेको नाम ',
                                            labelAlign: 'right',
                                            labelWidth: 230
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'btnAddCC',
                                            margin: '0 0 0 235',
                                            iconCls: 'icon-add',
                                            text: 'Add'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    margin: '0 3 0 0',
                                    width: 1030,
                                    autoScroll: true,
                                    title: 'कर मिलान दावी विवरण',
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            width: 1400,
                                            autoScroll: false,
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    width: 16
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '१'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '२'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '३'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '४'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 251,
                                                    text: '५'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '६'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '७'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '८'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '९'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '१०'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '११'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'label',
                                                    cls: 'LblCenter',
                                                    width: 91,
                                                    text: '१२'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            itemId: 'grdCC',
                                            margin: '0 0 5 0',
                                            minHeight: 50,
                                            width: 1400,
                                            autoScroll: false,
                                            hideHeaders: false,
                                            store: 'CreditClaimAnx10',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'rownumberer'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'CreditDocType',
                                                    text: 'कर दावीको किसिम'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'AccountCode',
                                                    text: 'राजश्व शिर्षक नमबर'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'CreditDocMode',
                                                    text: 'दाखीलाको तरिका'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'CreditDocNo',
                                                    text: 'दाखीला निस्सा नम्बर'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 260,
                                                    dataIndex: 'CreditBankCode',
                                                    text: 'बैंकको नाम'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    defaultWidth: 80,
                                                    dataIndex: 'CreditDocDate',
                                                    text: 'दाखीला मिति'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'CreditOffCode',
                                                    text: 'कार्यालय'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'WithTypeCode',
                                                    text: 'अग्रिम कर कट्टीको किसिम'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'WithHoldingPan',
                                                    text: 'अग्रिम कर कट्टी गर्नेको स्था.ले.नं. (भए)'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'WithAgentName',
                                                    text: 'अग्रिम कर कट्टी गर्नेको नाम'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    align: 'right',
                                                    dataIndex: 'CreditAmount',
                                                    text: 'दाखीला रकम'
                                                },
                                                {
                                                    xtype: 'actioncolumn',
                                                    itemId: 'lnkActionCC',
                                                    altText: 'Edit',
                                                    items: [
                                                        {
                                                            handler: function(view, rowIndex, colIndex, item, e) {
                                                                view.getSelectionModel().select(rowIndex);
                                                                var row = view.getStore().getAt(rowIndex);
                                                                MyApp.app.getController('CreditClaim').editCreditClaim(row);
                                                            },
                                                            icon: '../ITS/resources/images/icons/pencil.png',
                                                            iconCls: 'iconMargin',
                                                            tooltip: 'Edit'
                                                        },
                                                        {
                                                            handler: function(view, rowIndex, colIndex, item, e) {
                                                                var store = Ext.getStore("CreditClaimAnx10");
                                                                var row = store.getAt(rowIndex).data;

                                                                var txtTotCredit = Ext.ComponentQuery.query('#txtTotalCC')[0];
                                                                var creditAmt = (row.TotAmount === "")?0:row.CreditAmount;
                                                                var newTotCredit = 0;

                                                                Ext.Msg.confirm('Confirm Action', 'Do you want to Remove ?', function(btn) {
                                                                    if(btn == 'yes'){

                                                                        newTotCredit = parseFloat(txtTotCredit.getValue())-parseFloat(creditAmt);        
                                                                        txtTotCredit.setValue(newTotCredit);

                                                                        if(row.Action === "E")
                                                                        {
                                                                            row.Action = "D";        
                                                                            store.filter(function(item){
                                                                                return item.get("Action")!= 'D';
                                                                            });


                                                                            view.bindStore(store); 
                                                                        }
                                                                        else
                                                                        {
                                                                            store.removeAt(rowIndex);
                                                                        }

                                                                        return true;
                                                                    }
                                                                }, this);
                                                            },
                                                            icon: '../ITS/resources/images/icons/cancel.png',
                                                            iconCls: 'iconMargin',
                                                            tooltip: 'Delete'
                                                        }
                                                    ]
                                                }
                                            ],
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onGrdCCAfterRender,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'toolbar',
                                            margin: '-4 0 0 0 ',
                                            width: 1400,
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    margins: '0  0 1100',
                                                    width: 80,
                                                    text: 'Total Credit'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    margins: '0 5 ',
                                                    itemId: 'txtTotalCC',
                                                    width: 90,
                                                    fieldCls: 'TxtRight',
                                                    readOnly: true,
                                                    fieldLabel: ''
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            frame: true,
                            itemId: 'cntCC_button',
                            style: 'text-align:right;',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnCC_Save',
                                    margin: '10 5',
                                    iconCls: 'icon-save',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCC_submit',
                                    margin: '10 5',
                                    iconCls: 'icon-ok',
                                    text: 'Submit'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCC_Edit',
                                    margin: '10 5',
                                    iconCls: 'icon-edit',
                                    text: 'Edit'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnCC_Print',
                                    margin: '10 5',
                                    iconCls: 'icon-print',
                                    text: 'Print'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnCC_Verify',
                                    margin: '10 5',
                                    text: 'Verify'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCC_Delete',
                                    margin: '10 5',
                                    iconCls: 'icon-delete',
                                    text: 'Delete'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCC_Cancel',
                                    margin: '10 5',
                                    iconCls: 'icon-cancel',
                                    text: 'Cancel'
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'hdnCC_Office_Code',
                            fieldLabel: ''
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'hdnCC_Action',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'CCLoginOffcode',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'hdnCCTranNo',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTxtCreditDateAnx10Blur: function(field, options) {
        return validateFutureDate(field.getValue(),"Y",function(){field.focus();});
    },

    onGrdCCAfterRender: function(abstractcomponent, options) {
        var offCode = Ext.get('offCode').dom.innerHTML;

        Ext.ComponentQuery.query('#CCLoginOffcode')[0].setValue(offCode);
    }

});