/*
 * File: app/view/ManualCloseOfBusiness.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManualCloseOfBusiness', {
    extend: 'Ext.panel.Panel',

    itemId: 'ManualCloseOfBusiness',
    autoScroll: true,
    title: 'Close Of Business',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    frame: true,
                    itemId: 'frmManualCloseOfBusiness',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'container',
                            height: 160,
                            id: '',
                            itemId: 'cntHeaders',
                            style: 'font-size:18px;text-align:center;',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                padding: 5,
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'font-size:14px;',
                                    width: 500,
                                    text: 'अनुसुची - ११'
                                },
                                {
                                    xtype: 'label',
                                    style: 'font-size:11px;',
                                    width: 500,
                                    text: '(नियम १२ संग सम्बन्धित)'
                                },
                                {
                                    xtype: 'label',
                                    style: 'font-size:11px;',
                                    width: 500,
                                    text: 'नेपाल सरकार'
                                },
                                {
                                    xtype: 'label',
                                    style: 'font-size:11px;',
                                    width: 500,
                                    text: 'अर्थ मन्त्रालय'
                                },
                                {
                                    xtype: 'label',
                                    style: 'font-size:14px;',
                                    width: 500,
                                    text: 'आन्तरिक राजस्व बिभाग'
                                },
                                {
                                    xtype: 'label',
                                    height: 25,
                                    width: 500,
                                    text: 'मूल्य अभिबृध्दि कर विवरण फारम'
                                },
                                {
                                    xtype: 'label',
                                    height: 25,
                                    width: 500,
                                    text: '(कर योग्य कारोबार / कारोबार वन्द गर्ने अवस्थामा भर्ने)'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnRegistrationDate',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnVTaxyear',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnVFilingPeriod',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnNFText',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnActionType',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnAUOffCode',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hdnTranNo',
                                    fieldLabel: 'Label'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'cntYearMonthDesc',
                            padding: 5,
                            layout: {
                                columns: 4,
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    colspan: 4,
                                    disabled: false,
                                    itemId: 'txtSubmissionNo',
                                    margin: '0 0 5 0',
                                    name: 'txtPan',
                                    fieldLabel: 'सब्मिसन नं',
                                    labelWidth: 75,
                                    enforceMaxLength: true,
                                    maskRe: /[0-9]/,
                                    maxLength: 12,
                                    size: 14
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: false,
                                    itemId: 'txtPan',
                                    margin: '0 0 5 0',
                                    name: 'txtPan',
                                    fieldLabel: 'प्यान',
                                    labelWidth: 75,
                                    enforceMaxLength: true,
                                    maskRe: /[0-9]/,
                                    maxLength: 9,
                                    selectOnFocus: true,
                                    size: 14
                                },
                                {
                                    xtype: 'textfield',
                                    colspan: 3,
                                    disabled: false,
                                    itemId: 'txtAccountType',
                                    margin: '0 0 5 50',
                                    name: 'txtAccountType',
                                    readOnly: true,
                                    fieldLabel: 'खाताको किसिम',
                                    labelWidth: 90,
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maskRe: /[0-9]/,
                                    maxLength: 2,
                                    minLength: 2,
                                    size: 4
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'txtTaxYear',
                                    width: 150,
                                    name: 'txtTaxYear',
                                    fieldLabel: 'बर्ष',
                                    labelWidth: 75,
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 4,
                                    minLength: 4,
                                    size: 6,
                                    hideTrigger: true,
                                    keyNavEnabled: false,
                                    mouseWheelEnabled: false,
                                    decimalPrecision: 0,
                                    minValue: 2054
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'ddlFilingPeriod',
                                    margin: '0 0 0 50',
                                    fieldLabel: 'मा.\\ चौ. \\ व्दै',
                                    labelWidth: 90,
                                    emptyText: 'Select . . .',
                                    enableKeyEvents: true,
                                    size: 10,
                                    displayField: 'FilPeriodDesc',
                                    queryMode: 'local',
                                    store: 'FilingPeriodStore',
                                    valueField: 'FilPeriod'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'ddlPeriod',
                                    margin: '0 0 0 50',
                                    fieldLabel: 'महिना',
                                    labelWidth: 50,
                                    emptyText: 'Select . . .',
                                    enableKeyEvents: true,
                                    size: 10,
                                    editable: false,
                                    displayField: 'PeriodDesc',
                                    queryMode: 'local',
                                    valueField: 'Period'
                                },
                                {
                                    xtype: 'textfield',
                                    id: '',
                                    itemId: 'txtRecDate',
                                    margin: '0 0 0 50',
                                    fieldLabel: 'दाखिला मिति',
                                    labelWidth: 80,
                                    emptyText: 'YYYY.MM.DD',
                                    enforceMaxLength: true,
                                    maxLength: 10,
                                    minLength: 10,
                                    size: 12
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            frame: true,
                            height: 90,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'करदाताको विवरण',
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'lblTaxpayerName',
                                            padding: '5 0 0 0',
                                            width: 700,
                                            fieldLabel: 'नाम',
                                            labelWidth: 50
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        columns: 3,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'lblTaxpayerAddress',
                                            width: 300,
                                            name: 'lblTaxPayerAddress',
                                            fieldLabel: 'ठेगाना',
                                            labelWidth: 50
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'lblTaxpayerPhoneNo',
                                            margin: '0 0 0 50',
                                            width: 200,
                                            name: 'lblTaxpayerPhoneNo',
                                            fieldLabel: 'फोन नं',
                                            labelWidth: 50
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'lblTaxpayerFax',
                                            margin: '0 0 0 50',
                                            name: 'lblTaxpayerFax',
                                            fieldLabel: 'फ्याक्स नं'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            frame: true,
                            height: 820,
                            minHeight: 820,
                            autoScroll: false,
                            layout: {
                                align: 'stretch',
                                padding: '10 0 0 5',
                                type: 'vbox'
                            },
                            title: 'करदाताको कारोवार विवरण',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'यदि यस अवधिमा कारोवार नगरेको भए तलको महलमा शुन्य राखेर विवरणमा हस्ताक्षर गर्नुहोस्। रू १ भन्दा घटि भएमा पैसालाई रू. १ मा मिलान गरि विवरण भर्नुहोला।'
                                },
                                {
                                    xtype: 'container',
                                    cls: 'tablegrid',
                                    itemId: 'tablegrid',
                                    width: 700,
                                    layout: {
                                        columns: 4,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            style: 'margin-left:250px;',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<div style="width:100%;text-align:center">कारोबार मूल्य</div>',
                                            padding: '0 60 0 60',
                                            style: 'font-size:15px;',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<div style="width:100%;text-align:center">खरिदमा तिरेको कर क्रेडिट</div>',
                                            padding: '0 40 0 40',
                                            style: 'font-size:15px;',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<div style="width:100%;text-align:center">विक्रिमा तिरेको कर डेविट</div>',
                                            padding: '0 40 0 40',
                                            style: 'font-size:15px;',
                                            text: ''
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 4,
                                            style: 'font-size: 14px;',
                                            text: '१. विक्री'
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            width: 24,
                                            text: '१.१. कर लाग्ने बिक्री'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 2,
                                            itemId: 'txtTaxableSale',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtTaxableSale',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'txtVatOnSale',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtVatOnSale',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '१.२. निकासी'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 3,
                                            itemId: 'txtExport',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtExport',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '१.३. छुट विक्री'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 3,
                                            itemId: 'txtExemptSale',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtExemptSale',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 4,
                                            style: 'font-size: 14px;',
                                            text: '२. खरिद पैठारी'
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '२.१. कर लाग्ने खरीद'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'txtTaxablePurchase',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtTaxablePurchase',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 2,
                                            itemId: 'txtVatOnPurchase',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtVatOnPurchase',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '२.२. कर लाग्ने पैठारी'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            id: '',
                                            itemId: 'txtTaxablePurI',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtTaxablePurI',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 2,
                                            itemId: 'txtVatOnPurI',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtVatOnPurI',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '२.३. छुट खरिद'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 3,
                                            itemId: 'txtExemptPurchase',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtExemptPurchase',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            style: 'margin-left: 30px;',
                                            text: '२.४. छुट पैठारी'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 3,
                                            itemId: 'txtExemptPurI',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtExemptPurI',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 4,
                                            style: 'font-size: 14px;',
                                            text: '३. अन्य'
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 2,
                                            style: 'margin-left: 30px;',
                                            text: '३.१. अन्य थपघट'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'txtAdjCredit',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtAdjCredit',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'txtAdjDebit',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtAdjDebit',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 1,
                                            style: 'margin-left: 30px;',
                                            text: '३.२. कर कट्टी दाबी गरिसकेको स्टक'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 2,
                                            itemId: 'txtStockAmount',
                                            fieldStyle: 'text-align:right',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 1,
                                            itemId: 'txtStockTax',
                                            fieldStyle: 'text-align:right',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 2,
                                            style: 'font-size: 14px;',
                                            text: '४.जम्मा'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            disabled: false,
                                            itemId: 'txtTotalCredit',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtTotalCredit',
                                            readOnly: true,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            disabled: false,
                                            itemId: 'txtTotalDebit',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtTotalDebit',
                                            readOnly: true,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false,
                                            allowDecimals: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 3,
                                            margin: '5 0 0 0',
                                            style: 'font-size: 14px;',
                                            text: '५. डेविट-क्रेडिट            (‌‌+    वा    -)'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 1,
                                            cls: 'exclude',
                                            disabled: false,
                                            hidden: false,
                                            itemId: 'txtVatDueTM',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtVatDueTM',
                                            readOnly: true,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 3,
                                            margin: '5 0 0 0',
                                            style: 'font-size: 14px;',
                                            text: '६. गत महिनाको मिलन गर्न बांकी क्रेडिट'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 1,
                                            cls: 'exclude',
                                            disabled: false,
                                            itemId: 'txtCreditBF',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtCreditBF',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            keyNavEnabled: false,
                                            mouseWheelEnabled: false
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 3,
                                            margin: '5 0 0 0',
                                            style: 'font-size: 14px;',
                                            text: '७. तिर्नु पर्ने कर रू.(५-६)  (‌‌+ वा -)'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 1,
                                            cls: 'exclude',
                                            disabled: false,
                                            itemId: 'txtVatDue',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtVatDue',
                                            readOnly: true,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            mouseWheelEnabled: false
                                        },
                                        {
                                            xtype: 'label',
                                            colspan: 3,
                                            margin: '5 0 0 0',
                                            style: 'font-size: 14px;',
                                            text: '८. कर फिर्ता माग गरिएको रकम'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            colspan: 1,
                                            cls: 'exclude',
                                            itemId: 'txtRefClaimAmt',
                                            fieldStyle: 'text-align:right',
                                            name: 'txtRefClaimAmt',
                                            fieldBodyCls: '.TxtRight',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            disableKeyFilter: false,
                                            enforceMaxLength: true,
                                            maxLength: 14,
                                            size: 15,
                                            hideTrigger: true,
                                            mouseWheelEnabled: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    frame: true,
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            colspan: 1,
                                            margin: '0 0 0 5',
                                            style: 'font-size: 14px;',
                                            text: '९. कर फिर्ता माग गरेको अधार'
                                        },
                                        {
                                            xtype: 'combobox',
                                            colspan: 1,
                                            cls: 'exclude',
                                            hidden: true,
                                            itemId: 'ddlReferenceBasis',
                                            margin: '0 15 0 100',
                                            name: 'ddlReferenceBasis',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            size: 60,
                                            displayField: 'RBDescEng',
                                            store: 'ReferenceBasisStore',
                                            valueField: 'RBID'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'cntButtons',
                            padding: '0 0 0 400',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnSaveCloseOfBusiness',
                                    margin: '0 10 0 0',
                                    padding: 5,
                                    iconCls: 'icon-save',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnPrintCloseOfBusiness',
                                    margin: '0 10 0 0 ',
                                    padding: 5,
                                    iconCls: 'icon-print',
                                    text: 'Print'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSubmitCloseOfBusiness',
                                    margin: '0 10 0 0',
                                    padding: 5,
                                    iconCls: 'icon-ok',
                                    text: 'Submit'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnVerifyCloseOfBusiness',
                                    margin: '0 10 0 0',
                                    padding: 5,
                                    text: 'Verify'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnCOBBack',
                                    margin: '0 10 0 0',
                                    padding: 5,
                                    iconCls: 'icon-back',
                                    text: 'Back'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'hfCOBAction',
                                    fieldLabel: 'Label'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});