/*
 * File: app/view/SubmitError.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SubmitError', {
    extend: 'Ext.window.Window',

    height: 600,
    id: 'SubmitError',
    itemId: 'SubmitError',
    style: 'color:red;',
    width: 800,
    layout: {
        type: 'fit'
    },
    bodyStyle: 'color:red;',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    frame: true,
                    id: 'SubmitMessagePanel',
                    itemId: 'SubmitMessagePanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            frame: true,
                            id: 'PersonMessage',
                            itemId: 'PersonMessage',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Individual',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'PersonMessageTab',
                                itemId: 'PersonMessageTab'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    id: 'lblPerson',
                                    itemId: 'lblPerson',
                                    margin: 0,
                                    padding: 0,
                                    style: 'background-color:transparent;',
                                    fieldLabel: '',
                                    fieldStyle: 'background-color:transparent;'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            frame: true,
                            id: 'BusinessMessage',
                            itemId: 'BusinessMessage',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Income Tax',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'BusinessMessageTab',
                                itemId: 'BusinessMessageTab'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    id: 'lblBusiness',
                                    itemId: 'lblBusiness',
                                    fieldLabel: '',
                                    fieldStyle: 'background-color:transparent;'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            frame: true,
                            id: 'VATMessage',
                            itemId: 'VATMessage',
                            layout: {
                                type: 'fit'
                            },
                            title: 'VAT',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'VATMessageTab',
                                itemId: 'VATMessageTab'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    id: 'lblVat',
                                    itemId: 'lblVat',
                                    fieldLabel: '',
                                    fieldStyle: 'background-color:transparent;'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            frame: true,
                            id: 'ExciseMessage',
                            itemId: 'ExciseMessage',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Excise',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'ExciseMessageTab',
                                itemId: 'ExciseMessageTab',
                                width: 70
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    id: 'lblExcise',
                                    itemId: 'lblExcise',
                                    fieldLabel: '',
                                    fieldStyle: 'background-color:transparent;'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onSubmitMessagePanelAfterRender,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onSubmitMessagePanelAfterRender: function(component, eOpts) {
        var PopupWindow=Ext.ComponentQuery.query('#SubmitError')[0];
        PopupWindow.setTitle("<div style='color:red;'>Registration Information Saved Successfully But Submission Failed Because Following Fields Are Missing</div>");
        var panel=Ext.ComponentQuery.query('#SubmitMessagePanel')[0];

        var PersonMessage=Ext.ComponentQuery.query('#PersonMessageTab')[0];
        var BusinessMessage=Ext.ComponentQuery.query('#BusinessMessageTab')[0];
        var VATMessage=Ext.ComponentQuery.query('#VATMessageTab')[0];
        var ExciseMessage=Ext.ComponentQuery.query('#ExciseMessageTab')[0];

        var lblPerson=Ext.ComponentQuery.query('#lblPerson')[0];
        var lblBusiness=Ext.ComponentQuery.query('#lblBusiness')[0];
        var lblVat=Ext.ComponentQuery.query('#lblVat')[0];
        var lblExcise=Ext.ComponentQuery.query('#lblExcise')[0];

        PersonMessage.hide();
        BusinessMessage.hide();
        VATMessage.hide();
        ExciseMessage.hide();


        if(PopupWindow.extraParam.param)
        {
            var msgFor=PopupWindow.extraParam.param.messageForList;
            var msgLst=PopupWindow.extraParam.param.messageList;

            for(var c=0;c<msgLst.length;c++)
            {
                if(msgFor[c]=="Individual" && msgLst[c]!="")
                {
                    PersonMessage.show();
                    lblPerson.setValue(msgLst[c]);

                }
                else if(msgFor[c]=="ITAX" && msgLst[c]!="")
                {
                    BusinessMessage.show();
                    lblBusiness.setValue(msgLst[c]);


                }
                else if(msgFor[c]=="VAT" && msgLst[c]!="")
                {
                    VATMessage.show();
                    lblVat.setValue(msgLst[c]);

                }
                else if(msgFor[c]=="EXCISE" && msgLst[c]!="")
                {
                    ExciseMessage.show();
                    lblExcise.setValue(msgLst[c]);

                }
            }
        }


    }

});