/*
 * File: app/view/TDSWithholderCollRec.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TDSWithholderCollRec', {
    extend: 'Ext.panel.Panel',

    frame: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 30,
                    margin: '20 0 0 350',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            id: 'dpWCRTDSMsg',
                            itemId: 'dpWCRTDSMsg',
                            width: 250,
                            fieldStyle: '{     font-weight:bold; }'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'dpWCRTDSMsg1',
                            itemId: 'dpWCRTDSMsg1',
                            width: 80,
                            fieldStyle: '{     font-weight:bold; }'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'dpWCRTDSMsg2',
                            itemId: 'dpWCRTDSMsg2',
                            width: 20,
                            fieldStyle: '{     font-weight:bold; }'
                        },
                        {
                            xtype: 'displayfield',
                            id: 'dpWCRTDSMsg3',
                            itemId: 'dpWCRTDSMsg3',
                            width: 80,
                            fieldStyle: '{     font-weight:bold; }'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 340,
                            id: 'grdWCRTDSList',
                            itemId: 'grdWCRTDSList',
                            autoScroll: true,
                            store: 'TDSWithholderCollList',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 400,
                                    dataIndex: 'OfficeName',
                                    text: 'OfficeName'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 150,
                                    align: 'center',
                                    dataIndex: 'PaymentAmt',
                                    text: 'Amount'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 150,
                                    align: 'center',
                                    dataIndex: 'TDSAmt',
                                    text: 'TDS Amount'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    align: 'center',
                                    dataIndex: 'Count',
                                    text: 'Count'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 400,
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e) {
                                                var store = Ext.getStore('TDSWithholderCollList');
                                                var data = store.getAt(rowIndex).data;

                                                var hdnpan = Ext.ComponentQuery.query("#hdnWCRTDSpan")[0];
                                                hdnpan.setValue(data.WhPan);

                                                var action = Ext.ComponentQuery.query("#hdnWCRTDSaction")[0];
                                                action.setValue('Detail');
                                            },
                                            altText: 'Detail',
                                            icon: '../ITS/resources/images/icons/search.png',
                                            tooltip: 'Detail'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 50,
                                    id: 'grdWCRTDSSummary',
                                    itemId: 'grdWCRTDSSummary',
                                    hideHeaders: true,
                                    store: 'TDSWithCollSum',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 400,
                                            align: 'right',
                                            dataIndex: 'total',
                                            text: 'Total'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            align: 'center',
                                            dataIndex: 'totalAmt',
                                            text: 'TotalAmt'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            align: 'center',
                                            dataIndex: 'totalTDSAmt',
                                            text: 'TotalTDSAmt'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'totalVerCount',
                                            text: 'TotalVerCount'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWCRTDSiro',
                    itemId: 'hdnWCRTDSiro',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWCRTDSaction',
                    itemId: 'hdnWCRTDSaction',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWCRTDSfrom',
                    itemId: 'hdnWCRTDSfrom',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWCRTDSto',
                    itemId: 'hdnWCRTDSto',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWCRTDSpan',
                    itemId: 'hdnWCRTDSpan',
                    fieldLabel: 'Label'
                }
            ]
        });

        me.callParent(arguments);
    }

});