/*
 * File: app/view/Role.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Role', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.form.FieldContainer',
        'Ext.resizer.Splitter'
    ],

    frame: true,
    itemId: 'pnlRole',
    title: 'Role Form',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 3,
                    itemId: 'cntTop',
                    width: 800,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1.2,
                            itemId: 'cntApplicationList',
                            style: 'padding-top:5px;',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'role_grdApplication',
                                    title: 'Application List',
                                    hideHeaders: true,
                                    store: 'ApplicationWithMNR',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ApplicationID',
                                            text: 'ApplicationID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Description',
                                            text: 'Description'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 3,
                            margins: '',
                            itemId: 'cntRoleDetails',
                            style: 'padding-left:30px;',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: '',
                                    itemId: 'roleID',
                                    width: 400,
                                    fieldLabel: 'Role ID',
                                    msgTarget: 'side',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textareafield',
                                    itemId: 'roleDescription',
                                    width: 400,
                                    fieldLabel: 'Role Description'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'dbRole',
                                    width: 400,
                                    fieldLabel: 'DB Role'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'role_btnAddRole',
                                    margin: '0 0 0 352',
                                    iconCls: 'icon-add',
                                    text: 'add'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 4,
                    itemId: 'cntBottom',
                    margin: '5 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'cntRoleList',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'role_grdRole',
                                    width: 403,
                                    title: 'Role',
                                    columnLines: true,
                                    store: 'Role',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ApplicationID',
                                            text: 'Application ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'RoleID',
                                            text: 'Role ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'RoleDescription',
                                            text: 'Role Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'DbRole',
                                            text: 'Db Role'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'Action',
                                            text: 'Action'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'cntRoleModuleFunction',
                            style: 'padding-left:5px;',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'role_grdRoleModuleFunction',
                                    style: 'padding left:10px;',
                                    width: 515,
                                    title: 'Role Module Functions',
                                    columnLines: true,
                                    store: 'RoleModuleFunction',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ApplicationID',
                                            text: 'Application ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ModuleID',
                                            text: 'Module ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ModuleDesc',
                                            text: 'Module Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'FunCD',
                                            text: 'Function Code'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'FromDate',
                                            text: 'From Date'
                                        },
                                        {
                                            xtype: 'templatecolumn',
                                            tpl: [
                                                '<div> <input type="checkbox"  name ="chkFunc"    class="chkFunc"  id="chkFunc"/>  {FunDesc}</div>'
                                            ],
                                            width: 110,
                                            dataIndex: 'FunDesc',
                                            text: 'Function Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'FromDate',
                                            text: 'Action'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'old',
                                            text: 'old'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'FromDate',
                                            text: 'new'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 25,
                    itemId: 'btnFCnt',
                    margin: '5 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'splitter'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnRoleSave',
                            iconCls: 'icon-save',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnRoleCancel',
                            style: 'margin :0 0 0 10px;',
                            iconCls: 'icon-cancel',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});