/*
 * File: app/controller/CloseOffBusiness.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.CloseOffBusiness', {
    extend: 'Ext.app.Controller',

    onLblSubmissionNoCobClick: function(label) {
        var uiConfig = {menuLink:'GetGeneralizedSubmissionNo',pageTitle:'Close Off Business'};

        DynamicUI(uiConfig,function(){        

            Ext.ComponentQuery.query('#hdnGenLoginModule')[0].setValue("Income Tax System");
            Ext.ComponentQuery.query('#hdnGenLoginLeaf')[0].setValue("Close Off Business");

        },null);

        Ext.getCmp('CntSiteMapPath').update("Integrated Tax Menus >>Income Tax System >> Close Off Business");

    },

    onLblIncomeTaxCobClick: function(label) {
        var uiConfig = {menuLink:'GeneralizedLogin',pageTitle:'Generalized Login'};

        //var uiConfig = {menuLink:'VatReturnsSubNo',pageTitle:'Submission No'};
        DynamicUI(uiConfig,function(){        

            Ext.ComponentQuery.query('#hdnGenLoginModule')[0].setValue("Income Tax System");
            Ext.ComponentQuery.query('#hdnGenLoginLeaf')[0].setValue("Close Off Business");

        },null);

    },

    onLblTaxpayerLoginCobClick: function(label) {

    },

    init: function(application) {
        this.control({
            "#lblSubmissionNoCob": {
                click: this.onLblSubmissionNoCobClick
            },
            "#lblIncomeTaxCob": {
                click: this.onLblIncomeTaxCobClick
            },
            "#lblTaxpayerLoginCob": {
                click: this.onLblTaxpayerLoginCobClick
            }
        });
    }

});
