/*
 * File: app/controller/DocReqAssignment.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.DocReqAssignment', {
    extend: 'Ext.app.Controller',

    stores: [
        'strDocReqAssignment'
    ],
    views: [
        'DocReqAssignment'
    ],

    onDocReqAssignmentAfterRender: function(component, eOpts) {
        var me=this;

        var offCode=Ext.get('offCode').dom.innerHTML;
        var grdDocReqAssignment=Ext.ComponentQuery.query('#grdDocReqAssignment')[0];


        var watiMsg=waitMsg('Loading ...');

        Ext.Ajax.request
        ({

            url:'../Handlers/DocumentManagement/DocumentRequestHandler.ashx?method=GetAllDocReqAssignment',
            params:{REQ_OFFCODE:offCode},


            success:function(response){
                console.log(response.responseText);
                var obj =Ext.decode(response.responseText);
                var row = obj.root;
                console.log("row-->",obj.root);       

                grdDocReqAssignment.store.add(obj.root);
                watiMsg.hide();

            },

            failure:function(response)
            {
                msg('FAILURE',Ext.decode(response));

            }



        });
    },

    init: function(application) {
        this.control({
            "#DocReqAssignment": {
                afterrender: this.onDocReqAssignmentAfterRender
            }
        });
    }

});
