/*
 * File: app/controller/DocumentType.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.DocumentType', {
    extend: 'Ext.app.Controller',

    stores: [
        'DocType'
    ],

    onBtnDocSubmitClick: function(button, e, options) {

    },

    onGrdDocumentItemClick: function(tablepanel, record, item, index, e, options) {
        Ext.ComponentQuery.query('#txtDocTypeID')[0].setValue(record.data.DocTypeID);
        Ext.ComponentQuery.query('#txtDocTypeDescEn')[0].setValue(record.data.DocTypeDescEn);
        Ext.ComponentQuery.query('#txtDocTypeDescNp')[0].setValue(record.data.DocTypeDescNp);
        Ext.ComponentQuery.query('#chkDocStatus')[0].setValue(record.data.Status);

        Ext.ComponentQuery.query('#btnDocSubmit')[0].setText('Update');
    },

    init: function(application) {
        this.control({
            "#btnDocSubmit": {
                click: this.onBtnDocSubmitClick
            },
            "#grdDocument": {
                itemclick: this.onGrdDocumentItemClick
            }
        });
    }

});
